# Generated by Django 4.2.4 on 2023-08-12 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_job_company_address_job_company_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='Default name', max_length=10),
            preserve_default=False,
        ),
    ]
